spring.application.name=employee management system
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_system
spring.datasource.username=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.password=shehap12@
jwt.secret=shehap12@
jwt.expiration=840000